apiVersion: v1
kind: Pod
metadata:
  name: cpu-hog
  namespace: monitoring
  labels:
    app: cpu-hog
spec:
  containers:
    - name: hog
      image: busybox
      args:
        - /bin/sh
        - -c
        - "while true; do :; done"
