apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alert-rules
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
    - name: custom.rules
      rules:

        - alert: HighNodeCPU
          expr: (100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 70
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High CPU on {{ $labels.instance }}"
            description: "CPU usage is above 70% on {{ $labels.instance }} for more than 1 minute."

        - alert: HighNodeMemoryUsage
          expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage on {{ $labels.instance }}"
            description: "Memory usage is above 80% on {{ $labels.instance }}"

        - alert: PodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} is restarting frequently"
            description: "Container {{ $labels.container }} in pod {{ $labels.pod }} has restarted more than twice in the last 5 minutes."

        - alert: NodeDown
          expr: up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Node {{ $labels.instance }} is down"
            description: "Prometheus target {{ $labels.instance }} is not reachable"

        - alert: KubePodNotReady
          expr: kube_pod_status_ready{condition="true"} == 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} is not ready"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not ready for over 1 minute."
